version: "3"
services:
  web:
    container_name: campr-vulnerable-components-workshop
    image: openjdk:8-jdk-slim
    command: bash -c "cd /app && ./gradlew -g /app/.gradle appRun"
    volumes:
      - .:/app/
    ports:
      - "8080:9001"
